export const TAB_SESSION_PATH = 'tabSession.json'
export const TREE_SESSION_PATH = 'treeSession.json'
export const SIDE_SESSION_PATH = 'sideSession.json'
export const WINDOW_SESSION_PATH = 'windowSession.json'
export const TEMP_TRASH = 'trash'